/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.awt.Color;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class dlgViewStudentTime extends javax.swing.JDialog {

    /**
     * Creates new form dlgViewStudentTime
     */
    public dlgViewStudentTime(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        clsCon.inti();
        lblStudentName.setText("");
        lblCourse.setText("");
        lblYear.setText("");
        lblClass.setText("");
        lblSemester1.setText("");
        lblSemester.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtStudentID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblStudentName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblCourse = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        Class = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        txtArea15 = new javax.swing.JTextArea();
        txtSession1 = new javax.swing.JTextArea();
        txtSession2 = new javax.swing.JTextArea();
        jPanel20 = new javax.swing.JPanel();
        txtArea21 = new javax.swing.JTextArea();
        txtMonday1 = new javax.swing.JTextArea();
        txtMonday2 = new javax.swing.JTextArea();
        jPanel21 = new javax.swing.JPanel();
        txtArea24 = new javax.swing.JTextArea();
        txtWednesday1 = new javax.swing.JTextArea();
        txtWednesday2 = new javax.swing.JTextArea();
        jPanel24 = new javax.swing.JPanel();
        txtArea33 = new javax.swing.JTextArea();
        txtSaturday1 = new javax.swing.JTextArea();
        txtSaturday2 = new javax.swing.JTextArea();
        jPanel19 = new javax.swing.JPanel();
        txtArea18 = new javax.swing.JTextArea();
        txtTuesday1 = new javax.swing.JTextArea();
        txtTuesday2 = new javax.swing.JTextArea();
        jPanel22 = new javax.swing.JPanel();
        txtArea27 = new javax.swing.JTextArea();
        txtThursday1 = new javax.swing.JTextArea();
        txtThursday2 = new javax.swing.JTextArea();
        jPanel23 = new javax.swing.JPanel();
        txtArea30 = new javax.swing.JTextArea();
        txtFriday1 = new javax.swing.JTextArea();
        txtFriday2 = new javax.swing.JTextArea();
        lblSemester = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSemester1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtStudentID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtStudentID.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtStudentIDCaretUpdate(evt);
            }
        });
        txtStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentIDActionPerformed(evt);
            }
        });
        txtStudentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStudentIDKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Student ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Student Name");

        lblStudentName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblStudentName.setForeground(new java.awt.Color(0, 0, 255));
        lblStudentName.setText("Name");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Course");

        lblCourse.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblCourse.setForeground(new java.awt.Color(0, 0, 255));
        lblCourse.setText("Course");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Year");

        lblYear.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblYear.setForeground(new java.awt.Color(0, 0, 255));
        lblYear.setText("Year");

        Class.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        Class.setText("Class");

        lblClass.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblClass.setForeground(new java.awt.Color(0, 0, 255));
        lblClass.setText("Class");

        jPanel5.setBackground(new java.awt.Color(255, 153, 51));

        jPanel18.setBackground(new java.awt.Color(255, 153, 51));
        jPanel18.setFocusable(false);

        txtArea15.setColumns(20);
        txtArea15.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtArea15.setRows(5);
        txtArea15.setText("\nTime");
        txtArea15.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea15.setFocusable(false);

        txtSession1.setColumns(20);
        txtSession1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSession1.setRows(5);
        txtSession1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSession1.setFocusable(false);

        txtSession2.setColumns(20);
        txtSession2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSession2.setRows(5);
        txtSession2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSession2.setFocusable(false);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtArea15, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSession2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtArea15, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSession1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSession2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel20.setBackground(new java.awt.Color(255, 153, 51));
        jPanel20.setFocusable(false);

        txtArea21.setColumns(20);
        txtArea21.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtArea21.setRows(5);
        txtArea21.setText("\nMonday");
        txtArea21.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea21.setFocusable(false);

        txtMonday1.setColumns(20);
        txtMonday1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtMonday1.setRows(5);
        txtMonday1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMonday1.setFocusable(false);

        txtMonday2.setColumns(20);
        txtMonday2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtMonday2.setRows(5);
        txtMonday2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMonday2.setFocusable(false);

        jPanel21.setBackground(new java.awt.Color(255, 153, 51));
        jPanel21.setFocusable(false);

        txtArea24.setColumns(20);
        txtArea24.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtArea24.setRows(5);
        txtArea24.setText("\nWednesday\n");
        txtArea24.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea24.setFocusable(false);

        txtWednesday1.setColumns(20);
        txtWednesday1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtWednesday1.setRows(5);
        txtWednesday1.setText("\n");
        txtWednesday1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtWednesday1.setFocusable(false);

        txtWednesday2.setColumns(20);
        txtWednesday2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtWednesday2.setRows(5);
        txtWednesday2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtWednesday2.setFocusable(false);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtArea24, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtWednesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtWednesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtArea24, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtWednesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtWednesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel24.setBackground(new java.awt.Color(255, 153, 51));
        jPanel24.setFocusable(false);

        txtArea33.setColumns(20);
        txtArea33.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtArea33.setRows(5);
        txtArea33.setText("\nSaturday");
        txtArea33.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea33.setFocusable(false);

        txtSaturday1.setColumns(20);
        txtSaturday1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSaturday1.setRows(5);
        txtSaturday1.setText("\n");
        txtSaturday1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSaturday1.setFocusable(false);

        txtSaturday2.setColumns(20);
        txtSaturday2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSaturday2.setRows(5);
        txtSaturday2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtSaturday2.setFocusable(false);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtArea33, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSaturday1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtSaturday2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtArea33, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSaturday1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtSaturday2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel19.setBackground(new java.awt.Color(255, 153, 51));
        jPanel19.setFocusable(false);

        txtArea18.setColumns(20);
        txtArea18.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtArea18.setRows(5);
        txtArea18.setText("\nTuesday");
        txtArea18.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea18.setFocusable(false);

        txtTuesday1.setColumns(20);
        txtTuesday1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtTuesday1.setRows(5);
        txtTuesday1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTuesday1.setFocusable(false);

        txtTuesday2.setColumns(20);
        txtTuesday2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtTuesday2.setRows(5);
        txtTuesday2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTuesday2.setFocusable(false);

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtArea18, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtTuesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtTuesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtArea18, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtTuesday1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtTuesday2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel22.setBackground(new java.awt.Color(255, 153, 51));
        jPanel22.setFocusable(false);

        txtArea27.setColumns(20);
        txtArea27.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtArea27.setRows(5);
        txtArea27.setText("\nThursday\n");
        txtArea27.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea27.setFocusable(false);

        txtThursday1.setColumns(20);
        txtThursday1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtThursday1.setRows(5);
        txtThursday1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtThursday1.setFocusable(false);

        txtThursday2.setColumns(20);
        txtThursday2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtThursday2.setRows(5);
        txtThursday2.setText("\n");
        txtThursday2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtThursday2.setFocusable(false);

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtArea27, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtThursday1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtThursday2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtArea27, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtThursday1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtThursday2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel23.setBackground(new java.awt.Color(255, 153, 51));
        jPanel23.setFocusable(false);

        txtArea30.setColumns(20);
        txtArea30.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtArea30.setRows(5);
        txtArea30.setText("\nFriday\n");
        txtArea30.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtArea30.setFocusable(false);

        txtFriday1.setColumns(20);
        txtFriday1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtFriday1.setRows(5);
        txtFriday1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFriday1.setFocusable(false);

        txtFriday2.setColumns(20);
        txtFriday2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtFriday2.setRows(5);
        txtFriday2.setText("\n");
        txtFriday2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtFriday2.setFocusable(false);

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtArea30, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtFriday1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtFriday2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(txtArea30, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtFriday1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtFriday2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtArea21, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonday1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonday2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(txtArea21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtMonday1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(txtMonday2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblSemester.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSemester.setForeground(new java.awt.Color(0, 0, 255));
        lblSemester.setText("Semester");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Semester");

        lblSemester1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblSemester1.setForeground(new java.awt.Color(0, 0, 255));
        lblSemester1.setText("Semester");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(lblCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(83, 83, 83)
                            .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Class, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblClass, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblSemester1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSemester)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lblStudentName)
                    .addComponent(lblSemester))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblCourse)
                    .addComponent(jLabel5)
                    .addComponent(lblYear))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Class)
                    .addComponent(lblClass)
                    .addComponent(jLabel6)
                    .addComponent(lblSemester1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    void viewStudent(){  
        String s = null;
        String year = null;
        String se = null;
        lblStudentName.setText("");
        lblCourse.setText("");
        lblYear.setText("");
        lblClass.setText("");
        lblSemester1.setText("");        
        
        try{
            clsCon.setRs(clsCon.getStmt().executeQuery("select * from qStu where StuID='"+txtStudentID.getText()+"'"));      
            clsCon.getRs().first();
                lblStudentName.setText(clsCon.getRs().getString("StuName"));
                lblCourse.setText(clsCon.getRs().getString("CourseName"));                
                lblClass.setText(clsCon.getRs().getString("ClassName"));
                lblSemester.setText(clsCon.getRs().getString("Semester"));
                s = (String) clsCon.getRs().getString("Semester");
                switch(s){
                    case "1":   year = "I";     se = "I";    break;
                    case "2":   year = "I";     se = "II";   break;
                    case "3":   year = "II";    se = "I";    break;
                    case "4":   year = "II";    se = "II";   break;
                    case "5":   year = "III";   se = "I";    break;
                    case "6":   year = "III";   se = "II";   break;
                    case "7":   year = "IV";    se = "I";    break;
                    case "8":   year = "IV";    se = "II";   break;
                }                
                lblYear.setText(year);
                lblSemester1.setText(se);
        }catch(SQLException e){            
        }         
    }
    void clearText(){
        if(Integer.parseInt(lblSemester.getText())<5){
            txtSaturday1.setBackground(Color.white);
            txtSaturday2.setBackground(Color.white);
        }
        else{
            txtSaturday1.setBackground(Color.red);
            txtSaturday2.setBackground(Color.red);
        }
        txtSession1.setText("");
        txtSession2.setText("");
        txtMonday1.setText("");
        txtMonday2.setText("");
        txtTuesday1.setText("");
        txtTuesday2.setText("");
        txtWednesday1.setText("");
        txtWednesday2.setText("");
        txtThursday1.setText("");
        txtThursday2.setText("");
        txtFriday1.setText("");
        txtFriday2.setText("");
        txtSaturday1.setText("");
        txtSaturday2.setText("");
    }
    void viewStudentTime(){
        clearText();
        String subMo1 = null;
        String subTu1 = null;
        String subWe1 = null;
        String subTh1 = null;
        String subFr1 = null;
        String subSa1 = null;
        String subMo2 = null;
        String subTu2 = null;
        String subWe2 = null;
        String subTh2 = null;
        String subFr2 = null;
        String subSa2 = null;
        String type = null;
        
        String cl = ((String)lblClass.getText()).substring(0,1);
        if(cl.equals("A")||cl.equals("S")){
            txtSession1.setText("2:00pm - 3:30pm");
            txtSession2.setText("3:45pm - 5:15pm");
        }
        else if(cl.equals("M")){
            txtSession1.setText("7:00am - 8:30am");
            txtSession2.setText("8:45am - 10:15am");
        }
        else if(cl.equals("E")){
            txtSession1.setText("5:30pm - 7:00pm");
            txtSession2.setText("7:15pm - 8:45pm");
        }
       
        try {
            clsCon.setRs(clsCon.getStmt().executeQuery("select * from qTimetable where CourseName='"+lblCourse.getText()+"' and Semester="+lblSemester.getText()+" and ClassName='"+lblClass.getText()+"' and Active = 1"));
            
            
            if(clsCon.getRs().first()){  
                do{
                    if(clsCon.getRs().getByte("RoomType")==1){
                        if(clsCon.getRs().getString("Day").equals("Monday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                              
                                subMo1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtMonday1.setText(subMo1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Tuesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subTu1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtTuesday1.setText(subTu1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Wednesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subWe1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");                            
                                txtWednesday1.setText(subWe1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Thursday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subTh1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtThursday1.setText(subTh1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Friday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subFr1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtFriday1.setText(subFr1);                            
                            }
                        if(clsCon.getRs().getString("Day").equals("Saturday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subSa1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtSaturday1.setText(subSa1);
                            }

                        if(clsCon.getRs().getString("Day").equals("Monday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subMo2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtMonday2.setText(subMo2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Tuesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subTu2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtTuesday2.setText(subTu2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Wednesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subWe2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtWednesday2.setText(subWe2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Thursday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subTh2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");  
                                txtThursday2.setText(subTh2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Friday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subFr2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtFriday2.setText(subFr2);                            
                            }
                        if(clsCon.getRs().getString("Day").equals("Saturday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subSa2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtSaturday2.setText(subSa2);
                            }  
//                        if(txtSaturday1.getText() == null||txtSaturday1.getText().equals("")||txtSaturday2.getText() == null||txtSaturday2.getText().equals(""))
//                        {
//                            txtSaturday1.setBackground(Color.red);
//                            txtSaturday2.setBackground(Color.red);
//                        }
                    }
                    if(clsCon.getRs().getByte("RoomType")==2){
                        type = "Lab";
                        if(clsCon.getRs().getString("Day").equals("Monday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                              
                                subMo1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtMonday1.setText(subMo1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Tuesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subTu1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtTuesday1.setText(subTu1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Wednesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subWe1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");                            
                                txtWednesday1.setText(subWe1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Thursday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subTh1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtThursday1.setText(subTh1);
                            }
                        if(clsCon.getRs().getString("Day").equals("Friday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subFr1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtFriday1.setText(subFr1);                            
                            }
                        if(clsCon.getRs().getString("Day").equals("Saturday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session1")){                            
                                subSa1 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtSaturday1.setText(subSa1);
                            }

                        if(clsCon.getRs().getString("Day").equals("Monday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subMo2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtMonday2.setText(subMo2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Tuesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subTu2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtTuesday2.setText(subTu2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Wednesday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subWe2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtWednesday2.setText(subWe2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Thursday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subTh2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");  
                                txtThursday2.setText(subTh2);
                            }
                        if(clsCon.getRs().getString("Day").equals("Friday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subFr2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber");
                                txtFriday2.setText(subFr2);                            
                            }
                        if(clsCon.getRs().getString("Day").equals("Saturday"))
                            if(clsCon.getRs().getString("SessionName").equals("Session2")){                            
                                subSa2 = clsCon.getRs().getString("SubjectName") + "\n\r" + clsCon.getRs().getString("Name") + "\n\r" + type + " " +  clsCon.getRs().getString("Building") + clsCon.getRs().getString("RoomNumber"); 
                                txtSaturday2.setText(subSa2);
                            }  
//                        if(txtSaturday1.getText() == null||txtSaturday1.getText().equals("")||txtSaturday2.getText() == null||txtSaturday2.getText().equals(""))
//                        {
//                            txtSaturday1.setBackground(Color.red);
//                            txtSaturday2.setBackground(Color.red);
//                        }
                    }
                }while(clsCon.getRs().next());              
               
            }
        } catch (SQLException e) {
        }
    }
    private void txtStudentIDCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtStudentIDCaretUpdate
        viewStudent();
        viewStudentTime();
    }//GEN-LAST:event_txtStudentIDCaretUpdate

    private void txtStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentIDActionPerformed

    }//GEN-LAST:event_txtStudentIDActionPerformed

    private void txtStudentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIDKeyTyped

    }//GEN-LAST:event_txtStudentIDKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            clsCon.getCon().close(); 
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            clsCon.getCon().close(); 
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgViewStudentTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgViewStudentTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgViewStudentTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgViewStudentTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgViewStudentTime dialog = new dlgViewStudentTime(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                        try {
                            clsCon.getCon().close(); 
                        } catch (SQLException ex) {
                        }
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Class;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblCourse;
    private javax.swing.JLabel lblSemester;
    private javax.swing.JLabel lblSemester1;
    private javax.swing.JLabel lblStudentName;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTextArea txtArea15;
    private javax.swing.JTextArea txtArea18;
    private javax.swing.JTextArea txtArea21;
    private javax.swing.JTextArea txtArea24;
    private javax.swing.JTextArea txtArea27;
    private javax.swing.JTextArea txtArea30;
    private javax.swing.JTextArea txtArea33;
    private javax.swing.JTextArea txtFriday1;
    private javax.swing.JTextArea txtFriday2;
    private javax.swing.JTextArea txtMonday1;
    private javax.swing.JTextArea txtMonday2;
    private javax.swing.JTextArea txtSaturday1;
    private javax.swing.JTextArea txtSaturday2;
    private javax.swing.JTextArea txtSession1;
    private javax.swing.JTextArea txtSession2;
    private javax.swing.JTextField txtStudentID;
    private javax.swing.JTextArea txtThursday1;
    private javax.swing.JTextArea txtThursday2;
    private javax.swing.JTextArea txtTuesday1;
    private javax.swing.JTextArea txtTuesday2;
    private javax.swing.JTextArea txtWednesday1;
    private javax.swing.JTextArea txtWednesday2;
    // End of variables declaration//GEN-END:variables
}
