/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetable;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class dlgViewTeacherTime extends javax.swing.JDialog {

    /**
     * Creates new form dlgTeacherTime
     */
    public dlgViewTeacherTime(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        clsCon.inti();
        lblTeacherName.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTeacherID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblTeacherTime = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        lblTeacherName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txtTeacherID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtTeacherID.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTeacherIDCaretUpdate(evt);
            }
        });
        txtTeacherID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTeacherIDActionPerformed(evt);
            }
        });
        txtTeacherID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTeacherIDKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Teacher ID");

        jtblTeacherTime.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Course", "Subject", "Day", "Shift", "Session", "Class", "Room"
            }
        ));
        jScrollPane1.setViewportView(jtblTeacherTime);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Teacher Name");

        lblTeacherName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblTeacherName.setForeground(new java.awt.Color(0, 0, 255));
        lblTeacherName.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTeacherID, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(lblTeacherName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTeacherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTeacherName))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void viewTeacherTime(){    
        lblTeacherName.setText("");
        DefaultTableModel modeTbl;
        modeTbl = (DefaultTableModel)jtblTeacherTime.getModel();
        jtblTeacherTime.removeAll();
        try{
            clsCon.setRs(clsCon.getStmt().executeQuery("select * from qTimetable where TeacherID='"+txtTeacherID.getText()+"' and Active = 1"));      
            if(clsCon.getRs().first()){
                lblTeacherName.setText(clsCon.getRs().getString("Name"));
                do{
                    String course = clsCon.getRs().getString("CourseName");
                    String subject = clsCon.getRs().getString("SubjectName");
                    String day = clsCon.getRs().getString("Day");
                    String shift = clsCon.getRs().getString("ShiftName");
                    String session = clsCon.getRs().getString("SessionName");
                    String Class = clsCon.getRs().getString("ClassName");
                    String room = clsCon.getRs().getString("RoomNumber");
                    String build = clsCon.getRs().getString("Building");
                    room = build + room;
                    
                    if(shift.equals("Morning")){
                        if(session.equals("Session1"))
                            session = "7:00am - 8:30am";
                        if(session.equals("Session2"))
                            session = "8:45am - 10:15am";
                    }
                    if(shift.equals("Evening")){
                        if(session.equals("Session1"))
                            session = "5:30pm - 7:00pm";
                        if(session.equals("Session2"))
                            session = "7:15pm - 8:45pm";
                    }
                    if(shift.equals("Afternoon")){
                        if(session.equals("Session1"))
                            session = "2:00pm - 3:30pm";
                        if(session.equals("Session2"))
                            session = "3:45pm - 5:15pm";
                    }
                   
                    String st[]={course,subject,day,shift,session,Class,room};

                    modeTbl.addRow(st);
                }while(clsCon.getRs().next());
            } 
        }catch(SQLException e){            
        }         
    }
    private void txtTeacherIDCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTeacherIDCaretUpdate
        int i=0;
        DefaultTableModel modeTbl;
        modeTbl = (DefaultTableModel)jtblTeacherTime.getModel();
        if(jtblTeacherTime.getRowCount()>0)
        do{
                modeTbl.removeRow(jtblTeacherTime.getRowCount()-1);                
            }while(jtblTeacherTime.getRowCount()>0);
        viewTeacherTime();
    }//GEN-LAST:event_txtTeacherIDCaretUpdate

    private void txtTeacherIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTeacherIDActionPerformed
        
    }//GEN-LAST:event_txtTeacherIDActionPerformed

    private void txtTeacherIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeacherIDKeyTyped

    }//GEN-LAST:event_txtTeacherIDKeyTyped

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        try {
            clsCon.getCon().close();
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            clsCon.getCon().close(); 
        } catch (SQLException ex) {
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgViewTeacherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgViewTeacherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgViewTeacherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgViewTeacherTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dlgViewTeacherTime dialog = new dlgViewTeacherTime(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                        try {
                            clsCon.getCon().close(); 
                        } catch (SQLException ex) {
                        }
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblTeacherTime;
    private javax.swing.JLabel lblTeacherName;
    private javax.swing.JTextField txtTeacherID;
    // End of variables declaration//GEN-END:variables
}
